# Generated by Django 5.2.4 on 2025-07-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='confirmPassword',
            field=models.CharField(default='temp1234', max_length=128),
        ),
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default='temp1234', max_length=128),
        ),
    ]
